openapi: 3.0.0
info:
  title: Bareja HMS API
  description: API for accessing Hospital Management System data
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /api/doctors:
    get:
      summary: Get all doctors
      responses:
        '200':
          description: A JSON array of doctors
  /api/departments:
    get:
      summary: Get all departments
      responses:
        '200':
          description: A JSON array of departments
  /api/department:
    post:
      summary: Create a new department
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Department created
  /api/department/{id}:
    put:
      summary: Update a department
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Updated successfully
    delete:
      summary: Delete a department
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Deleted successfully